sudo: false

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

cache:
  - pip

install:
  - pip install -r requirements.txt

script:
  - flake8 censusbatchgeocoder
  - coverage run setup.py test
  - coverage report -m

after_success:
 - coveralls
